name: Metrics
on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SIKAI-C
          
          template: classic
          base: header, repositories
          
          # Remove default activity
          plugin_activity: no
          
          # Add 3D calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          config_theme: github_dark