name: Metrics

on:
  schedule: [{cron: "0 3 * * *"}]
  workflow_dispatch:

jobs:

  calendar:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SIKAI-C
          filename: metrics-calendar.svg
          base: header
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SIKAI-C
          filename: metrics-habits.svg
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: no

  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SIKAI-C
          filename: metrics-activity.svg
          plugin_activity: yes
          plugin_activity_limit: 5
